<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Wshop | Ecommerce</title>

        <link rel="stylesheet"  type="text/css" href="css/style.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    
    </head>

    <body>

        <div id="container">
            <div class="lista">
                <a class="link" href="/listarprodutos">Listar produtos</a>
                <a class="link" href="/listarfornecedores">Listar fornecedores</a>
            </div>
            <div class="lista">
                <a class="link" href="/cadastrarproduto">Cadastrar produtos</a>
                <a class="link" href="/cadastrarfornecedor">Cadastrar fornecedor</a>
            </div>
        </div>
    </body>
</html>